backend:
  name: git-gateway
  repo: truust-io/docs.truust.io
publish_mode: editorial_workflow
media_folder: static/assets
public_folder: assets
collections:
  - name: content
    label: Article
    folder: content
    create: true
    fields:
      - { name: title, label: Title }
      - { name: metaTitle, label: 'Meta Title', required: false }
      - { name: metaDescription, label: 'Meta Description', widget: 'text', required: false }
      - { name: body, label: Body, widget: markdown }
